cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/cask-fonts"

brew "exa"
brew "git"
brew "jq"
brew "rsync"
brew "tree"
brew "watch"

cask "appcleaner"
cask "google-chrome"
cask "iterm2"
cask "keyboardcleantool"
brew "mkdocs"
brew "mysql-client"
brew "node"
brew "openjdk@11"
brew "pyenv"
brew "qemu"
brew "starship"
brew "wget"
brew "yarn"
cask "alfred"
cask "bettertouchtool"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-hack-nerd-font"
cask "font-ricty-diminished"
cask "google-japanese-ime"
cask "iterm2"
cask "karabiner-elements"
cask "keyboardcleantool"
cask "kindle"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "the-unarchiver"
cask "visual-studio-code"
